apiVersion: v1
kind: Service
metadata:
  name: django-api-srvc
spec:
  type: NodePort
  selector:
    app: django-app
  ports:
    - name: django-app
      protocol: TCP
      port: 8000
      targetPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: django-postgres-srvc
  labels:
    app: django
spec:
  ports:
    - port: 5432
  selector:
    app: django
    tier: postgres
  clusterIP: None
