name: CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

  dockerize:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Minikube
        uses: medyagh/setup-minikube@master

      - name: Build Docker image
        run: |
          eval $(minikube -p minikube docker-env)
          docker build -t django-app:latest .

  deployment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Minikube
        uses: medyagh/setup-minikube@master

      - name: Apply Kubernetes manifests
        run: |
          kubectl apply -f infra/k8s/storage.yaml
          kubectl apply -f infra/k8s/deployment.yaml
          kubectl apply -f infra/k8s/services.yaml

      - name: Test service URLs
        run: |
          kubectl get services
          minikube service list
