name: CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  build-dockerise-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: dockerise
        uses: medyagh/setup-minikube@master
      - name: Build Docker image
        run: |
          export SHELL=/bin/bash
          eval $(minikube -p minikube docker-env)
          docker build -t django-app:latest .
          docker images

      - name: Deploy
        run: |
          kubectl apply -f infra/k8s/storage.yaml
          kubectl apply -f infra/k8s/deployment.yaml
          kubectl apply -f infra/k8s/services.yaml

      - name: Test service
        run: |
          minikube service list
