name: CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

  dockerize:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build -f ./Dockerfile.dev -t django-app:latest .
          docker images

  deployment:
    runs-on: ubuntu-latest
    needs: dockerize

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Minikube
        run: |

      - name: Install Minikube
        run: |
          curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
          chmod +x minikube
          sudo mv minikube /usr/local/bin/

      - name: Start Minikube
        run: |
          minikube start

      - name: Check Minikube Status
        run: |
          minikube status

      - name: Set Docker Environment
        run: |
          eval $(minikube -p minikube docker-env)

      - name: Load Docker image into Minikube
        run: |
          docker save django-app:latest | (eval $(minikube docker-env --shell bash) && docker load)

      - name: Apply Kubernetes manifests
        run: |
          eval $(minikube -p minikube docker-env)
          kubectl apply -f infra/k8s/storage.yaml
          kubectl apply -f infra/k8s/deployment.yaml
          kubectl apply -f infra/k8s/services.yaml

      - name: Test service
        run: |
          minikube service list
