name: CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

  dockerize:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Build Docker image
        run: |
          docker build -t django-app:latest .
          docker images
          minikube image load django-app:latest

  deployment:
    runs-on: ubuntu-latest
    needs: dockerize

    steps:
      - name: Apply Kubernetes manifests
        run: |
          kubectl apply -f infra/k8s/storage.yaml
          kubectl apply -f infra/k8s/deployment.yaml
          kubectl apply -f infra/k8s/services.yaml

      - name: Test service
        run: |
          kubectl get services
          minikube service list
